name: 'CI'
on:
  push:
    branches:
    - main
    - features/**
    tags:
    - '*.*.*'
  pull_request:
env:
  DOTNET_NOLOGO: true
premissions:
  packages: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        runs-on: [macOS-latest, ubuntu-latest, windows-latest]
    name: ${{ matrix.runs-on }}
    runs-on: ${{ matrix.runs-on }}
    steps:
    - name: Setup dotNet 3.x
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 3.1.x
    - uses: actions/checkout@af513c7a016048ae468971c52ed77d9562c7c819
    - run: dotnet --info
    
    - if: contains(matrix.runs-on, 'macOS') || contains(matrix.runs-on, 'ubuntu')
      run: ./build.sh
    - if: matrix.runs-on == 'windows-latest' && github.ref != 'refs/heads/main' && !contains(github.ref, 'refs/tags/')
      run: ./build.ps1
    - if: (matrix.runs-on == 'windows-latest') && (github.ref == 'refs/heads/main' || contains(github.ref, 'refs/tags/'))
      env:
        SignClientSecret: ${{ secrets.SIGNCLIENT }}
      run: |
        ./build.ps1 sign
        dotnet nuget push .\nuget\*.nupkg -s https://nuget.pkg.github.com/your-username/index.json -k ${{ secrets.GITHUB_TOKEN }}
